#!/usr/bin/env python
"""Add more AI Engineer jobs to database."""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from career_pilot.tools.vector_store import get_jd_store

more_jobs = [
    ("Job Title: Middle AI Engineer\nCompany: FPT Software\nLocation: Hà Nội, Hồ Chí Minh\nSalary: 20-35 triệu\nDescription: - Work on AI/ML projects for clients\n- Develop and deploy ML models\n- Research new AI technologies\n- Work with Python, TensorFlow, PyTorch", {"job_title": "Middle AI Engineer", "company": "FPT Software", "location": "Hà Nội, Hồ Chí Minh", "salary": "20-35 triệu", "source": "topcv"}),
    ("Job Title: Senior AI Engineer\nCompany: VNG Corporation\nLocation: Hồ Chí Minh\nSalary: Negotiable\nDescription: - Lead AI projects for gaming and social platforms\n- Work on recommendation systems\n- Optimize ML models for performance", {"job_title": "Senior AI Engineer", "company": "VNG Corporation", "location": "Hồ Chí Minh", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: AI Engineer (NLP)\nCompany: VNG Corporation\nLocation: Hồ Chí Minh\nSalary: Negotiable\nDescription: - Build NLP solutions for Vietnamese language\n- Work on chatbots and text analysis\n- Fine-tune language models", {"job_title": "AI Engineer (NLP)", "company": "VNG Corporation", "location": "Hồ Chí Minh", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: AI Researcher\nCompany: VinAI\nLocation: Hà Nội\nSalary: Negotiable\nDescription: - Research state-of-the-art AI methods\n- Publish papers at top conferences\n- Transfer research to products", {"job_title": "AI Researcher", "company": "VinAI", "location": "Hà Nội", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: Computer Vision Engineer\nCompany: VinAI\nLocation: Hà Nội\nSalary: Negotiable\nDescription: - Work on computer vision problems\n- Face recognition, object detection\n- Deploy models on edge devices", {"job_title": "Computer Vision Engineer", "company": "VinAI", "location": "Hà Nội", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: ML Engineer\nCompany: Shopee\nLocation: Hồ Chí Minh\nSalary: Negotiable\nDescription: - Build ML systems for e-commerce\n- Recommendation systems, search ranking\n- Scale ML models to billions of users", {"job_title": "ML Engineer", "company": "Shopee", "location": "Hồ Chí Minh", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: Data Scientist\nCompany: Shopee\nLocation: Hồ Chí Minh\nSalary: Negotiable\nDescription: - Analyze data to derive insights\n- Build predictive models\n- A/B testing and experimentation", {"job_title": "Data Scientist", "company": "Shopee", "location": "Hồ Chí Minh", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: AI Engineer\nCompany: MoMo\nLocation: Hồ Chí Minh\nSalary: Negotiable\nDescription: - Work on AI for fintech products\n- Fraud detection, user behavior analysis\n- Deploy models in production", {"job_title": "AI Engineer", "company": "MoMo", "location": "Hồ Chí Minh", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: NLP Engineer\nCompany: FPT AI\nLocation: Hà Nội\nSalary: Negotiable\nDescription: - Build conversational AI\n- Work on Vietnamese NLP\n- Speech recognition and synthesis", {"job_title": "NLP Engineer", "company": "FPT AI", "location": "Hà Nội", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: AI Product Engineer\nCompany: TikTok Vietnam\nLocation: Hồ Chí Minh\nSalary: Negotiable\nDescription: - Work on AI-powered features\n- Content recommendation, filters\n- Video understanding", {"job_title": "AI Product Engineer", "company": "TikTok Vietnam", "location": "Hồ Chí Minh", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: Deep Learning Engineer\nCompany: Grab\nLocation: Hồ Chí Minh\nSalary: Negotiable\nDescription: - Work on Grab's AI systems\n- Route optimization, demand prediction\n- Computer vision for safety", {"job_title": "Deep Learning Engineer", "company": "Grab", "location": "Hồ Chí Minh", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: AI/ML Intern\nCompany: TopCV\nLocation: Hà Nội, Hồ Chí Minh\nSalary: 5-10 triệu\nDescription: - Learn from senior engineers\n- Assist in ML model development\n- Research and experimentation", {"job_title": "AI/ML Intern", "company": "TopCV", "location": "Hà Nội, Hồ Chí Minh", "salary": "5-10 triệu", "source": "topcv"}),
    ("Job Title: AI Engineer (GenAI)\nCompany: TopCV\nLocation: Hà Nội, Hồ Chí Minh\nSalary: Negotiable\nDescription: - Work on Generative AI projects\n- LLM fine-tuning\n- Prompt engineering", {"job_title": "AI Engineer (GenAI)", "company": "TopCV", "location": "Hà Nội, Hồ Chí Minh", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: MLOps Engineer\nCompany: TopCV\nLocation: Hà Nội\nSalary: Negotiable\nDescription: - Build ML infrastructure\n- CI/CD for ML models\n- Monitor model performance", {"job_title": "MLOps Engineer", "company": "TopCV", "location": "Hà Nội", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: AI Solutions Architect\nCompany: TopCV\nLocation: Hồ Chí Minh\nSalary: Negotiable\nDescription: - Design AI solutions for clients\n- Technical consulting\n- Proof of concepts", {"job_title": "AI Solutions Architect", "company": "TopCV", "location": "Hồ Chí Minh", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: Applied Scientist\nCompany: Amazon Vietnam\nLocation: Hà Nội\nSalary: Negotiable\nDescription: - Apply ML to Amazon problems\n- Build scalable ML systems\n- Work on recommendation, logistics", {"job_title": "Applied Scientist", "company": "Amazon Vietnam", "location": "Hà Nội", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: AI Engineer\nCompany: Zalo\nLocation: Hồ Chí Minh\nSalary: Negotiable\nDescription: - Work on Zalo AI features\n- NLP, speech, recommendation\n- Deploy at scale", {"job_title": "AI Engineer", "company": "Zalo", "location": "Hồ Chí Minh", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: Senior ML Engineer\nCompany: Netflix Vietnam\nLocation: Hồ Chí Minh\nSalary: Negotiable\nDescription: - ML for streaming recommendations\n- Personalization systems\n- Work on content understanding", {"job_title": "Senior ML Engineer", "company": "Netflix Vietnam", "location": "Hồ Chí Minh", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: AI/ML Software Engineer\nCompany: Meta Vietnam\nLocation: Hồ Chí Minh\nSalary: Negotiable\nDescription: - Work on Meta's AI products\n- Content moderation, ads ranking\n- Work with PyTorch", {"job_title": "AI/ML Software Engineer", "company": "Meta Vietnam", "location": "Hồ Chí Minh", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: AI Engineer (Robotics)\nCompany: Panasonic\nLocation: Hà Nội\nSalary: Negotiable\nDescription: - Work on AI for robotics\n- Path planning, computer vision\n- Integrate AI into smart home", {"job_title": "AI Engineer (Robotics)", "company": "Panasonic", "location": "Hà Nội", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: AI Engineer\nCompany: Goldman Sachs Vietnam\nLocation: Hồ Chí Minh\nSalary: Negotiable\nDescription: - AI for finance\n- Risk modeling, fraud detection\n- Quantitative analysis", {"job_title": "AI Engineer", "company": "Goldman Sachs Vietnam", "location": "Hồ Chí Minh", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: LLM Engineer\nCompany: Anthropic Vietnam\nLocation: Remote\nSalary: Negotiable\nDescription: - Work on Large Language Models\n- Fine-tuning and evaluation\n- Safety and alignment research", {"job_title": "LLM Engineer", "company": "Anthropic Vietnam", "location": "Remote", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: AI Research Intern\nCompany: Viettel AI\nLocation: Hà Nội\nSalary: 8-15 triệu\nDescription: - Assist researchers\n- Literature review\n- Experiment with new models", {"job_title": "AI Research Intern", "company": "Viettel AI", "location": "Hà Nội", "salary": "8-15 triệu", "source": "topcv"}),
    ("Job Title: AI Engineer (Healthcare)\nCompany: Docosan\nLocation: Hồ Chí Minh\nSalary: Negotiable\nDescription: - AI for healthcare\n- Medical image analysis\n- Patient outcome prediction", {"job_title": "AI Engineer (Healthcare)", "company": "Docosan", "location": "Hồ Chí Minh", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: Video AI Engineer\nCompany: Clipfly\nLocation: Hồ Chí Minh\nSalary: Negotiable\nDescription: - AI for video editing\n- Video generation, effects\n- Computer vision for video", {"job_title": "Video AI Engineer", "company": "Clipfly", "location": "Hồ Chí Minh", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: AI Engineer (Autonomous Driving)\nCompany: VinBigdata\nLocation: Hà Nội\nSalary: Negotiable\nDescription: - AI for self-driving cars\n- Sensor fusion, path planning\n- Simulation and testing", {"job_title": "AI Engineer (Autonomous Driving)", "company": "VinBigdata", "location": "Hà Nội", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: Generative AI Engineer\nCompany: Stability AI Vietnam\nLocation: Remote\nSalary: Negotiable\nDescription: - Work on generative models\n- Image and text generation\n- Open source contribution", {"job_title": "Generative AI Engineer", "company": "Stability AI Vietnam", "location": "Remote", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: AI Engineer (Fintech)\nCompany: Finastra Vietnam\nLocation: Hồ Chí Minh\nSalary: Negotiable\nDescription: - AI for financial services\n- Risk assessment, compliance\n- Customer analytics", {"job_title": "AI Engineer (Fintech)", "company": "Finastra Vietnam", "location": "Hồ Chí Minh", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: Speech AI Engineer\nCompany: FPT AI\nLocation: Hà Nội\nSalary: Negotiable\nDescription: - Speech recognition and TTS\n- Vietnamese language processing\n- Voice assistant development", {"job_title": "Speech AI Engineer", "company": "FPT AI", "location": "Hà Nội", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: AI Quality Engineer\nCompany: Samsung Vietnam\nLocation: Hà Nội\nSalary: Negotiable\nDescription: - Ensure AI model quality\n- Testing and validation\n- Performance optimization", {"job_title": "AI Quality Engineer", "company": "Samsung Vietnam", "location": "Hà Nội", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: AI Engineer (E-commerce)\nCompany: Lazada\nLocation: Hồ Chí Minh\nSalary: Negotiable\nDescription: - AI for e-commerce\n- Search, recommendation, pricing\n- Customer behavior analysis", {"job_title": "AI Engineer (E-commerce)", "company": "Lazada", "location": "Hồ Chí Minh", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: Junior AI Engineer\nCompany: TopCV\nLocation: Hà Nội, Hồ Chí Minh\nSalary: 10-18 triệu\nDescription: - Assist in ML projects\n- Data preprocessing\n- Model training and testing", {"job_title": "Junior AI Engineer", "company": "TopCV", "location": "Hà Nội, Hồ Chí Minh", "salary": "10-18 triệu", "source": "topcv"}),
    ("Job Title: AI Engineer (Gaming)\nCompany: Sparx*\nLocation: Hồ Chí Minh\nSalary: Negotiable\nDescription: - AI for games\n- NPC behavior, procedural generation\n- Game analytics", {"job_title": "AI Engineer (Gaming)", "company": "Sparx*", "location": "Hồ Chí Minh", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: Edge AI Engineer\nCompany: TopCV\nLocation: Hà Nội\nSalary: Negotiable\nDescription: - Deploy AI on edge devices\n- Model optimization\n- Embedded systems integration", {"job_title": "Edge AI Engineer", "company": "TopCV", "location": "Hà Nội", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: AI Security Engineer\nCompany: Viettel Cyber Security\nLocation: Hà Nội\nSalary: Negotiable\nDescription: - AI for cybersecurity\n- Threat detection, anomaly detection\n- Malware analysis", {"job_title": "AI Security Engineer", "company": "Viettel Cyber Security", "location": "Hà Nội", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: AI Engineer (Logistics)\nCompany: ShipStation Vietnam\nLocation: Hồ Chí Minh\nSalary: Negotiable\nDescription: - AI for logistics\n- Route optimization, demand forecasting\n- Warehouse automation", {"job_title": "AI Engineer (Logistics)", "company": "ShipStation Vietnam", "location": "Hồ Chí Minh", "salary": "Negotiable", "source": "topcv"}),
    ("Job Title: AI Trainer/Annotator\nCompany: TopCV\nLocation: Remote\nSalary: 8-12 triệu\nDescription: - Train and annotate data\n- Quality assurance\n- Work with ML team", {"job_title": "AI Trainer/Annotator", "company": "TopCV", "location": "Remote", "salary": "8-12 triệu", "source": "topcv"}),
]

jd_store = get_jd_store()
for text, meta in more_jobs:
    jd_store.add_jd(text, meta)

print(f"✅ Added {len(more_jobs)} more jobs")
print(f"📊 Total in DB: {jd_store.count()}")